### ISSUE TITLE
Client Secret question of this library

### ISSUE THREAD

**Issue by yuchaozh** [google/gtm-oauth2#44]
Hi all,

I am trying to use this library for youtube oauth. I encounter a question, right now, there is no client secret anymore, but this library is still using client secret in the example. How can I avoid to use the client secret?

Thanks a lot.

**Comment by yzhong52** [comment]
I am having the exact same problem. Thanks for asking!

**Comment by yuchaozh** [comment]
Have you solve the issue? I just use "others" instead of "IOS" to get credential in google developer console.

**Comment by yzhong52** [comment]
Nope, no really looking now. But maybe you can give this one a try: https://github.com/JonasGessner/google-api-objectivec-client It is a fixed by JonasGessner.

**Comment by thomasvl** [comment]
The secret can be empty - https://github.com/google/gtm-oauth2/wiki#registering-your-application

Note: [GTMAppAuth](https://github.com/google/GTMAppAuth) is now provided by Google's identity teams and uses the required out of proc webviews to do signins; so gtm-oauth2 is being deprecated.
