### ISSUE TITLE
The operation couldn’t be completed. (com.google.GTMOAuth2 error -1001.) From NC Widget

### ISSUE THREAD

**Issue by eytanschulman** [google/gtm-oauth2#59]
I'm getting this error when trying to perform a simple calendar query from an NC Widget. The same query works fine from it's parent app. Is there a place where I could see what error -1001 means?

**Comment by thomasvl** [comment]
The NSError should have some more info in the userInfo.  It might also be useful to turn on the fetcher logging https://github.com/google/google-api-objectivec-client/wiki#logging-http-server-traffic

**Comment by eytanschulman** [comment]
@thomasvl After creating a shared keychain between my parent app and extension, it works! Thank you very much, I suggest possibly adding this tip to the wiki at some point :+1:

**Comment by thomasvl** [comment]
Glad to hear it.

I need to find the time to do a bunch of docs cleanups/additions.  :(

(I really wish github supported pull requests for wikis to suggest edits…)
