### ISSUE TITLE
GTMOAuth2Authentication.h file not found 

### ISSUE THREAD

**Issue by sid26ag** [google/gtm-oauth2#71]
The example project DriveSample detected with an issue while compiling .

**Comment by thomasvl** [comment]
There's no Drive Sample with this project. Which sample are you specifically talking about?  [google-api-objectivec-client-for-rest](https://github.com/google/google-api-objectivec-client-for-rest) and the older [google-api-objectivec-client](https://github.com/google/google-api-objectivec-client) both have Drive examples, and both seen to be able to build.  They do use git submodules to pull in dependencies, so you do need to make sure you git checkout is recursive.

**Comment by shyamalschandra** [comment]
@thomasvl: What do you mean by "submodules to pull in dependencies"?  How do I get the examples to work without any changes with the gtm-oauth2?

**Comment by thomasvl** [comment]
Same comment about examples holds, this project doesn't have examples, which ones are you talking about?

Assuming you mean the others I listed, `git clone --recursive [url]` will checkout out the module with the dependencies when you first clone it.  Failing that `git submodule update --remote` should fetch them into something already checked out.
