### ISSUE TITLE
canAuthorize returns false in simulator but true on real device (iOS 10)

### ISSUE THREAD

**Issue by metagon** [google/gtm-oauth2#76]
Hello,

I'm currently developing an app that uses Google authentication that stores the token in the keychain.
Today I updated to Xcode 8/Swift 3 etc. and noticed a strange issue that only occurs on the simulator. After successfully logging in, I can make requests to the backend and everything works fine, but when I relaunch the App, it asks me to log in again. Seems like it can't access the keychain. On my physical device, this doesn't happen.

Thank you in advance!

**Comment by thomasvl** [comment]
There's a bug in the iOS 10 simulator keychain support where things like to error out (that used to work).  So we're looking at hacking around it by just using NSUserDefaults for that one configuration.

**Comment by metagon** [comment]
Thank you for the quick response. I was going mad about this issue, trying to figure out what's wrong with my code.

**Comment by thomasvl** [comment]
Fyi - https://github.com/google/gtm-oauth2/pull/77 in flight.  I might not do a CocoaPods release right away just to confirm this doesn't cause other problems.
