### ISSUE TITLE
default scopes added automatically?

### ISSUE THREAD

**Issue by klwinkel** [google/gtm-oauth2#78]
I am requesting DriveFile acces for my app, but always also get email and userprofile too in the window were the user needs to grant access.
is this normal?

this is my code:

GTMOAuth2ViewControllerTouch *authViewController =
    [[GTMOAuth2ViewControllerTouch alloc] initWithScope:kGTLRAuthScopeDriveFile
                                               clientID:kClientId
                                               clientSecret:nil
                                               keychainItemName:kKeychainItemName
                                               delegate:self
                                               finishedSelector:finishedSelector];

**Comment by thomasvl** [comment]
Since most apps end up wanting to disable a little info about the user (_Logged in as User \<user@gmail.com\>_), the code defaults to adding the scopes and fetching that info.  See the header for more info:

https://github.com/google/gtm-oauth2/blob/master/Source/GTMOAuth2SignIn.h#L95-L104
