### ISSUE TITLE
Google calendar issues 

### ISSUE THREAD

**Issue by ChildDivin** [google/gtm-oauth2#80]
Hello team, I hope you are doing great. I face some issue when I implement **Google calendar sync** from my iphone sdk .

1> **Login screen** :- When Present Login screen there are not way to back to the application (Cancel Login )

2> **Save Login session**  :- I can not save session for while (When I kill my app and relaunch app it's ask to login again , In google calendar sdk )

Thanks for your support .

Thanks and regard,
 Developer

**Comment by thomasvl** [comment]
For 1 it is really going to depend on how you present the controller, do you provide a means to go back?  Check the wiki on [presenting](https://github.com/google/gtm-oauth2/wiki#displaying-the-controllers) the controller.

For 2, is this on a device or the simulator?  I'm assuming you are checking the keychain to reload things?  ([Docs](https://github.com/google/gtm-oauth2/wiki#retrieving-authorization-from-the-keychain))
