### ISSUE TITLE
Is this deprecated now?

### ISSUE THREAD

**Issue by jostster** [google/gtm-oauth2#84]
With google soon restricting embedded web view auth https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html will this become deprecated or will it update to fit the requirements?

**Comment by thomasvl** [comment]
We're going to go ahead and deprecate this as there are some other alternatives now that also include support for things like tvOS.  Just merged in a PR to add a notice here, and we will be working on updating the samples in projects that used to depend on this.

**Comment by fisherds** [comment]
Just wanted to say thanks for adding the link to the new approach for iOS Endpoints developers.  Time to start learning GTMAppAuth I guess.  It's got most of the same letters even, how hard can it be to learn something new. ;)

**Comment by jostster** [comment]
@thomasvl can you advise on how GTMAppAuth is different? It looks like it still uses a webview. Apple has been rejecting applications that open up safari for 3rd party authentication.
