### ISSUE TITLE
403. That's an error

### ISSUE THREAD

**Issue by khuong291** [google/gtm-oauth2#87]

**Comment by khuong291** [comment]
This user-agent is not permitted to make an OAuth authorization request to Google as It is classified as an embedded user-agent...

**Comment by thomasvl** [comment]
Please see the [deprecation notice](https://github.com/google/gtm-oauth2#warning-deprecation-notice)

Duplicate of #84 & #85

**Comment by khuong291** [comment]
Hi @thomasvl , so I should use https://github.com/google/GTMAppAuth instead?

**Comment by thomasvl** [comment]
Yup

**Comment by khuong291** [comment]
Thank you :dancing_men:
