### ISSUE TITLE
Can't build Examples/OAuth2Sample

### ISSUE THREAD

**Issue by KondrikA** [google/gtm-oauth2#89]
Hi
By default needed GTMSessionFetcherOSX.framework. I can't find it.
If I try use GTMSessionFetcher through pod-file the project still does not compile.
xCode 8.2.1

**Comment by KondrikA** [comment]
sorry, i find https://github.com/google/gtm-session-fetcher

**Comment by thomasvl** [comment]
You likely want to look at https://github.com/google/GTMAppAuth, see - https://github.com/google/gtm-oauth2#warning-deprecation-notice for some links to more info.
