### ISSUE TITLE
GTMOAuth2-iOS target copies Info.plist as a bundle resource.

### ISSUE THREAD

**Issue by otto-schnurr** [google/gtm-oauth2#91]
I'm seeing this when running Analyze on the `GTMOAuth2-iOS` target in Xcode 8.3 (8E162):

> Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'GTMOAuth2-iOS/Info.plist'.

It looks like Apple has a [technical note on how to fix this](https://developer.apple.com/library/content/qa/qa1649/_index.html).

**Comment by thomasvl** [comment]
Can you share some more info?  Are you using CocoaPods or the checked in project?  The checked in project here doesn't have a target by that name, and the podspec here doesn't reference any info.plist files, so it doesn't appear to be coming from here either.

**Comment by otto-schnurr** [comment]
Oops. My mistake. We're using an Xcode workspace for integration. It looks like that target is something we made locally.

Thanks for the quick reply Thomas. I appreciate it. Sorry for the trouble.
