### ISSUE TITLE
Is GTMOAuth2WindowController something we can still use after the embedded webview deprecation?

### ISSUE THREAD

**Issue by MattyAyOh** [google/gtm-oauth2#93]
As per 
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

> In the coming months, we will no longer allow OAuth requests to Google in embedded browsers known as “web-views”,

We have been using `GTMOAuth2WIndowController` in our desktop app, which seem like would fall under "embedded web-view"

and noticed that the requests being sent had `Chrome, Safari, etc` in the `user-agent` header of the request, even though the web request was coming from our app

We also didn't see the deprecation warning, though according to the blogpost, the warning only appears for iOS and Android?

So just quick question, is this something we need to be worrying about if we are using `GTMOAuth2WindowController`?

**Comment by thomasvl** [comment]
Yup - https://github.com/google/gtm-oauth2#warning-deprecation-notice.

You'll need to migrate per that announcement.

**Comment by MattyAyOh** [comment]
ah, brilliant 

*slaps forehead*

thanks for the reply
