### ISSUE TITLE
My app crash when calling "GIDSignIn.sharedInstance().signIn()" at second run or another later

### ISSUE THREAD

**Issue by o0oKodako0o** [google/gtm-oauth2#95]
I'm working with an iOS project that using Google SignIn services.

It seems to be ok at the first time running when I call "GIDSignIn.sharedInstance().signIn()" and "GIDSignIn.sharedInstance().signOut()" continuously.

In next running, when I call "GIDSignIn.sharedInstance().signIn()", my app crashs at function:
- (GTMOAuth2Fetcher *)beginTokenFetchWithDelegate:(id)delegate
                              didFinishSelector:(SEL)finishedSel {}
of GTMOAuth2Authentication.m.

Please help me to solve this problem. Thank you very much!

P/s: My pod version is 1.2.0.
I add 'Google/SignIn' to pod file and details info after running "pod install"
Using FirebaseAnalytics (3.8.0)
Using FirebaseCore (3.6.0)
Using FirebaseInstanceID (1.0.10)
Using GTMOAuth2 (1.1.4)
Using GTMSessionFetcher (1.1.9)
Using Google (3.0.3)
Using GoogleSignIn (4.0.2)
Using GoogleToolboxForMac (2.1.1)

Crash screenshot:
<img src="https://image.ibb.co/iORLbQ/Screen_Shot_2017_04_17_at_4_18_03_PM.png" alt="Screen_Shot_2017_04_17_at_4_18_03_PM" border="0">

**Comment by thomasvl** [comment]
If you are using GoogleSignIn, I don't think you need to have GTMOAuth2 also, and GoogleSignIn might have some of the same class names (it was using an old copy of GTMOAuth2 at one point).  I'd suggest opening a bug with that library since that appears to be where the problems are starting from and not directly from this library.

**Comment by o0oKodako0o** [comment]
Hello Thomas

As I mentioned above, I added only 'Google/SingIn' in Podfile but after run '"pod install", there are some others were installed include GTMOAuth2.

**Comment by thomasvl** [comment]
Sorry, missed that.  Rest of the comment still holds.  We aren't very familiar with the GoogleSignIn library, so I'd suggest using their documented help places.

**Comment by kiraniphone** [comment]
Any update on this?

**Comment by kiraniphone** [comment]
@kodakvn did you find any fix for this?
