### ISSUE TITLE
Warnings against Swift 4

### ISSUE THREAD

**Issue by ulukaya** [google/gtm-oauth2#97]
GTMOAuth2/Source/Touch/GTMOAuth2ViewControllerTouch.m:390:23: 

This function declaration is not a prototype

**Comment by thomasvl** [comment]
I'm not completely sure what that warning is trying to flag given the line number reference or why the content of a .m file would apply to Swift 4; I'd expect Swift issues to maybe relate to the .h files.

But please note, [gtm-oauth2 has been deprecated](https://github.com/google/gtm-oauth2#warning-deprecation-notice); embedded webview are no longer supporting for signing into Google accounts, GTMAppAuth or Google Sign-In should be used instead and they also provide objects that implement the `GTMFetcherAuthorizationProtocol` to integrate with other libraries.

**Comment by ghowen** [comment]
I am getting something similar with Xcode 9 GM and a Swift 3.2 project:

Pods/GTMOAuth2/Source/Touch/GTMOAuth2ViewControllerTouch.m:390:23: This block declaration is not a prototype

I am not using gtm-oauth2 directly. It is a dependency of GoogleSignIn (4.1.0) which is a dependency of FirebaseUI/Google (4.2.0).

**Comment by thomasvl** [comment]
Pushed a 1.1.5 pod with the source tweak that will hopefully avoid this.

**Comment by ghowen** [comment]
Thanks. Looks good on my machine. One warning down, some more to go ;)
